# Generated by Django 4.1.7 on 2023-03-09 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consulta_tipodocumento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('desc', models.CharField(blank=True, max_length=36)),
                ('abrev', models.CharField(blank=True, max_length=24)),
            ],
            options={
                'db_table': 'Consulta_tipodocumento',
            },
        ),
        migrations.CreateModel(
            name='Consulta_tipoNovedad',
            fields=[
                ('idtiponovedad', models.AutoField(primary_key=True, serialize=False)),
                ('desc', models.CharField(blank=True, max_length=36)),
            ],
            options={
                'db_table': 'Consulta_tiponovedad',
            },
        ),
        migrations.CreateModel(
            name='tmp_consulta_personasisben',
            fields=[
                ('primak', models.AutoField(primary_key=True, serialize=False)),
                ('id', models.IntegerField(blank=True, null=True)),
                ('ficha', models.TextField(blank=True, null=True)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('fecharegsdm', models.DateField(blank=True, db_column='FechaRegSDM', null=True)),
                ('tipodocumento_id', models.IntegerField(blank=True, db_column='tipodocumento_id', null=True)),
                ('documen', models.TextField(blank=True, null=True)),
                ('ape1', models.CharField(blank=True, max_length=135)),
                ('ape2', models.CharField(blank=True, max_length=135)),
                ('nom1', models.CharField(blank=True, max_length=135)),
                ('nom2', models.CharField(blank=True, max_length=135)),
                ('sexo', models.IntegerField(blank=True, null=True)),
                ('tiponovedad_id', models.IntegerField(blank=True, db_column='tiponovedad_id', null=True)),
                ('placa', models.CharField(blank=True, db_column='Placa', max_length=135)),
                ('fechanto', models.DateField(blank=True, null=True)),
                ('edad', models.IntegerField(blank=True, db_column='Edad', null=True)),
                ('fechaentregatarjeta', models.DateField(blank=True, db_column='fechaEntregaTarjeta', db_index=True, null=True)),
                ('nombarrio', models.CharField(blank=True, max_length=45)),
                ('direccion', models.CharField(blank=True, max_length=45)),
                ('telefono', models.CharField(blank=True, max_length=45)),
                ('comuna', models.CharField(blank=True, max_length=45)),
            ],
            options={
                'db_table': 'tmp_consulta_personasisben',
            },
        ),
        migrations.CreateModel(
            name='eliminar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documen', models.CharField(blank=True, max_length=36)),
                ('tipodoc', models.IntegerField(blank=True)),
            ],
            options={
                'db_table': 'eliminar',
                'unique_together': {('tipodoc', 'documen')},
            },
        ),
        migrations.CreateModel(
            name='consulta_personasisben',
            fields=[
                ('primak', models.IntegerField(blank=True, null=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ficha', models.TextField(blank=True, null=True)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('fecharegsdm', models.DateField(blank=True, db_column='FechaRegSDM', null=True)),
                ('documen', models.CharField(blank=True, max_length=36)),
                ('ape1', models.CharField(blank=True, max_length=135)),
                ('ape2', models.CharField(blank=True, max_length=135)),
                ('nom1', models.CharField(blank=True, max_length=135)),
                ('nom2', models.CharField(blank=True, max_length=135)),
                ('sexo', models.IntegerField(blank=True, null=True)),
                ('placa', models.CharField(blank=True, db_column='Placa', max_length=135)),
                ('fechanto', models.DateField(blank=True, null=True)),
                ('edad', models.IntegerField(blank=True, db_column='Edad', null=True)),
                ('fechaentregatarjeta', models.DateField(blank=True, db_column='fechaEntregaTarjeta', db_index=True, null=True)),
                ('nombarrio', models.CharField(blank=True, max_length=45)),
                ('direccion', models.CharField(blank=True, max_length=45)),
                ('telefono', models.CharField(blank=True, max_length=45)),
                ('comuna', models.CharField(blank=True, max_length=45)),
                ('tipodocumento_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='file.consulta_tipodocumento')),
                ('tiponovedad_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='file.consulta_tiponovedad')),
            ],
            options={
                'db_table': 'consulta_personasisben',
            },
        ),
    ]
