# Generated by Django 4.1.7 on 2023-03-09 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tmp_consulta_personasisben',
            name='fecha',
        ),
        migrations.RemoveField(
            model_name='tmp_consulta_personasisben',
            name='fechaentregatarjeta',
        ),
        migrations.RemoveField(
            model_name='tmp_consulta_personasisben',
            name='fecharegsdm',
        ),
    ]
