# Generated by Django 4.1.7 on 2023-03-09 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0003_tmp_consulta_personasisben2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tmp_consulta_personasisben2',
            name='ids',
        ),
    ]
