# Generated by Django 4.1.7 on 2023-03-09 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0004_remove_tmp_consulta_personasisben2_ids'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consulta_personasisben',
            old_name='tipodocumento_id',
            new_name='tipodocumento',
        ),
        migrations.RenameField(
            model_name='consulta_personasisben',
            old_name='tiponovedad_id',
            new_name='tiponovedad',
        ),
    ]
