# Generated by Django 4.1.7 on 2023-03-09 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0006_delete_tmp_consulta_personasisben2_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consulta_personasisben',
            old_name='tipodocumento_id',
            new_name='tipodocumento',
        ),
        migrations.RenameField(
            model_name='consulta_personasisben',
            old_name='tiponovedad_od',
            new_name='tiponovedad',
        ),
    ]
