# Generated by Django 4.1.7 on 2023-03-09 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0008_remove_consulta_personasisben_fecha_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulta_personasisben',
            name='tipodocumento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='file.consulta_tipodocumento'),
        ),
        migrations.AlterField(
            model_name='consulta_personasisben',
            name='tiponovedad',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='file.consulta_tiponovedad'),
        ),
    ]
