# Generated by Django 4.1.7 on 2023-03-29 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0009_alter_consulta_personasisben_tipodocumento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tmp_consulta_personasisben',
            name='puntaje_sisbn',
            field=models.CharField(blank=True, max_length=45),
        ),
    ]
